# https://github.com/marketplace/actions/run-julia-package-tests
name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read


jobs:
  build:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.8']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          annotate: true
