# Adapted from
# https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  Documentation:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_DEBUG: true
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'
          julia --project=. docs/make.jl
